# Generated by Django 5.1.1 on 2024-10-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_storage_document_remove_storage_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.FileField(upload_to='uploads/files/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
