# Generated by Django 5.1.1 on 2024-10-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='file',
        ),
    ]
