# Generated by Django 5.1.1 on 2024-10-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_remove_archive_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('archive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filearchive_archive', to='archives.archive')),
            ],
        ),
    ]
